# Generated by Django 5.2.13 on 2026-04-14 00:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bjcp_code', models.CharField(blank=True, help_text='e.g. 21A', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('hop_type', models.CharField(choices=[('bittering', 'Bittering'), ('aroma', 'Aroma'), ('dual', 'Dual Purpose')], default='dual', max_length=20)),
                ('form', models.CharField(choices=[('pellet', 'Pellet'), ('whole', 'Whole / Leaf'), ('plug', 'Plug'), ('cryo', 'Cryo / LupuLN2')], default='pellet', max_length=20)),
                ('alpha_acid_pct', models.FloatField(help_text='Alpha acid % (e.g. 12.5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aroma_profile', models.TextField(blank=True, help_text='e.g. citrus, pine, tropical')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('producer', models.CharField(blank=True, max_length=100)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('malt_type', models.CharField(choices=[('base', 'Base Malt'), ('caramel', 'Caramel / Crystal'), ('roasted', 'Roasted'), ('adjunct', 'Adjunct / Sugar'), ('other', 'Other')], default='base', max_length=20)),
                ('color_ebc', models.FloatField(help_text='Color in EBC units', validators=[django.core.validators.MinValueValidator(0)])),
                ('potential_sg', models.FloatField(blank=True, help_text='Max extract potential (e.g. 1.037)', null=True)),
                ('moisture_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text='e.g. WY1056, WLP001, US-05', max_length=30)),
                ('yeast_type', models.CharField(choices=[('ale', 'Ale'), ('lager', 'Lager'), ('wheat', 'Wheat / Weizen'), ('wild', 'Wild / Brett'), ('hybrid', 'Hybrid / Kveik'), ('other', 'Other')], default='ale', max_length=20)),
                ('temp_min_c', models.FloatField(help_text='Min fermentation temp (°C)')),
                ('temp_max_c', models.FloatField(help_text='Max fermentation temp (°C)')),
                ('alcohol_tolerance', models.FloatField(blank=True, help_text='Max ABV tolerance (%)', null=True)),
                ('flavor_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('batch_size_l', models.FloatField(help_text='Target batch size in litres', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('boil_volume_l', models.FloatField(help_text='Pre-boil volume in litres', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('boil_time_min', models.IntegerField(help_text='Boil duration in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('efficiency_pct', models.FloatField(default=75, help_text='Brewhouse efficiency %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('og', models.FloatField(help_text='Original Gravity (e.g. 1.060)', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('fg', models.FloatField(help_text='Final Gravity (e.g. 1.012)', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('abv', models.FloatField(help_text='Alcohol By Volume %', validators=[django.core.validators.MinValueValidator(0)])),
                ('ibu', models.FloatField(help_text='International Bitterness Units', validators=[django.core.validators.MinValueValidator(0)])),
                ('ebc', models.FloatField(help_text='Colour in EBC units', validators=[django.core.validators.MinValueValidator(0)])),
                ('srm', models.FloatField(blank=True, help_text='Colour in SRM units', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.beerstyle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MashStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Saccharification Rest', max_length=100)),
                ('step_type', models.CharField(choices=[('infusion', 'Infusion'), ('decoction', 'Decoction'), ('temperature', 'Temperature (HERMS/RIMS)'), ('sparge', 'Sparge')], default='infusion', max_length=20)),
                ('temp_c', models.FloatField(help_text='Target temperature in °C')),
                ('time_min', models.IntegerField(help_text='Hold time in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('water_l', models.FloatField(blank=True, help_text='Strike/infusion water volume (litres)', null=True)),
                ('water_temp_c', models.FloatField(blank=True, help_text='Strike water temperature (°C)', null=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mash_steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FermentationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('primary', 'Primary Fermentation'), ('secondary', 'Secondary / Conditioning'), ('dry_hop', 'Dry Hop Rest'), ('lagering', 'Lagering / Cold Crash'), ('carbonation', 'Carbonation')], default='primary', max_length=20)),
                ('temp_c', models.FloatField(help_text='Temperature in °C')),
                ('duration_days', models.IntegerField(help_text='Duration in days', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermentation_steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeHop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('use', models.CharField(choices=[('first_wort', 'First Wort'), ('boil', 'Boil'), ('whirlpool', 'Whirlpool / Flameout'), ('dry_hop', 'Dry Hop')], default='boil', max_length=20)),
                ('time_min', models.IntegerField(help_text='Minutes before end of boil (boil/whirlpool), or days (dry hop)', validators=[django.core.validators.MinValueValidator(0)])),
                ('ibu_contribution', models.FloatField(blank=True, help_text='Calculated IBU contribution', null=True)),
                ('hop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.hop')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-time_min'],
            },
        ),
        migrations.CreateModel(
            name='RecipeMalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.FloatField(blank=True, help_text='% of total grain bill (auto-calculated or manual)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('malt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.malt')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malts', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-amount_kg'],
            },
        ),
        migrations.CreateModel(
            name='WaterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calcium_ppm', models.FloatField(default=0)),
                ('magnesium_ppm', models.FloatField(default=0)),
                ('sodium_ppm', models.FloatField(default=0)),
                ('chloride_ppm', models.FloatField(default=0)),
                ('sulfate_ppm', models.FloatField(default=0)),
                ('bicarbonate_ppm', models.FloatField(default=0)),
                ('ph', models.FloatField(blank=True, help_text='Target mash pH', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_profile', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeYeast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Packets (dry) or mL (liquid)', validators=[django.core.validators.MinValueValidator(0)])),
                ('starter', models.BooleanField(default=False)),
                ('starter_size_l', models.FloatField(blank=True, help_text='Starter volume in litres', null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeasts', to='recipes.recipe')),
                ('yeast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.yeast')),
            ],
        ),
    ]
