# Generated by Django 5.2.13 on 2026-04-30 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mashstep',
            name='water_l',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='alcohol_tolerance',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='code',
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='bjcp_code',
            field=models.CharField(blank=True, help_text='ex: 21A', max_length=10),
        ),
        migrations.AlterField(
            model_name='fermentationstep',
            name='duration_days',
            field=models.IntegerField(help_text='Duração em dias', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fermentationstep',
            name='stage',
            field=models.CharField(choices=[('primary', 'Fermentação Primária'), ('secondary', 'Secundária / Condicionamento'), ('dry_hop', 'Repouso Dry Hop'), ('lagering', 'Lagering / Cold Crash'), ('carbonation', 'Carbonatação')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='fermentationstep',
            name='temp_c',
            field=models.FloatField(help_text='Temperatura em °C'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='alpha_acid_pct',
            field=models.FloatField(help_text='Porcentagem de alfa ácido (ex: 12.5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='hop',
            name='aroma_profile',
            field=models.TextField(blank=True, help_text='ex: cítrico, tropical'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='form',
            field=models.CharField(choices=[('pellet', 'Pellet'), ('whole', 'Flor / Folha'), ('plug', 'Plug'), ('cryo', 'Cryo / LupuLN2')], default='pellet', max_length=20),
        ),
        migrations.AlterField(
            model_name='hop',
            name='hop_type',
            field=models.CharField(choices=[('bittering', 'Amargor'), ('aroma', 'Aroma'), ('dual', 'Duplo Propósito')], default='dual', max_length=20),
        ),
        migrations.AlterField(
            model_name='malt',
            name='color_ebc',
            field=models.FloatField(help_text='Cor em unidades EBC', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='malt',
            name='malt_type',
            field=models.CharField(choices=[('base', 'Malte Base'), ('caramel', 'Caramel / Cristal'), ('roasted', 'Torrado'), ('adjunct', 'Adjunto / Açúcar'), ('other', 'Outro')], default='base', max_length=20),
        ),
        migrations.AlterField(
            model_name='malt',
            name='potential_sg',
            field=models.FloatField(blank=True, help_text='Potencial máximo de extrato (ex: 1.037)', null=True),
        ),
        migrations.AlterField(
            model_name='mashstep',
            name='name',
            field=models.CharField(help_text='ex: Repouso de Sacarificação', max_length=100),
        ),
        migrations.AlterField(
            model_name='mashstep',
            name='step_type',
            field=models.CharField(choices=[('infusion', 'Infusão'), ('decoction', 'Decocção'), ('temperature', 'Temperatura (HERMS/RIMS)'), ('sparge', 'Lavagem')], default='infusion', max_length=20),
        ),
        migrations.AlterField(
            model_name='mashstep',
            name='temp_c',
            field=models.FloatField(help_text='Temperatura alvo em °C'),
        ),
        migrations.AlterField(
            model_name='mashstep',
            name='time_min',
            field=models.IntegerField(help_text='Tempo de repouso em minutos', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mashstep',
            name='water_temp_c',
            field=models.FloatField(blank=True, help_text='Temperatura da água de infusão (°C)', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='abv',
            field=models.FloatField(help_text='Teor alcoólico %', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='batch_size_l',
            field=models.FloatField(help_text='Volume final do lote em litros', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='boil_time_min',
            field=models.IntegerField(help_text='Duração da fervura em minutos', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='boil_volume_l',
            field=models.FloatField(help_text='Volume pré-fervura em litros', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ebc',
            field=models.FloatField(help_text='Cor em unidades EBC', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='efficiency_pct',
            field=models.FloatField(default=65, help_text='Eficiência da cervejaria %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fg',
            field=models.FloatField(help_text='Densidade Final (ex: 1.012)', validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ibu',
            field=models.FloatField(help_text='Unidades Internacionais de Amargor', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='og',
            field=models.FloatField(help_text='Densidade Original (ex: 1.060)', validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='srm',
            field=models.FloatField(blank=True, help_text='Cor em unidades SRM', null=True),
        ),
        migrations.AlterField(
            model_name='recipehop',
            name='ibu_contribution',
            field=models.FloatField(blank=True, help_text='Contribuição calculada de IBU', null=True),
        ),
        migrations.AlterField(
            model_name='recipehop',
            name='time_min',
            field=models.IntegerField(help_text='Minutos antes do fim da fervura (fervura/whirlpool), ou dias (dry hop)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipehop',
            name='use',
            field=models.CharField(choices=[('first_wort', 'Mosto Primário'), ('boil', 'Fervura'), ('whirlpool', 'Whirlpool'), ('dry_hop', 'Dry Hop')], default='boil', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipemalt',
            name='percentage',
            field=models.FloatField(blank=True, help_text='% do total de grãos', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='recipeyeast',
            name='amount',
            field=models.FloatField(help_text='Pacotes (dry) ou mL (líquida)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipeyeast',
            name='starter_size_l',
            field=models.FloatField(blank=True, help_text='Volume do starter em litros', null=True),
        ),
        migrations.AlterField(
            model_name='waterprofile',
            name='ph',
            field=models.FloatField(blank=True, help_text='pH alvo do mosto', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='temp_max_c',
            field=models.FloatField(help_text='Temperatura máxima de fermentação (°C)'),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='temp_min_c',
            field=models.FloatField(help_text='Temperatura mínima de fermentação (°C)'),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='yeast_type',
            field=models.CharField(choices=[('ale', 'Ale'), ('lager', 'Lager'), ('wheat', 'Trigo / Weizen'), ('wild', 'Selvagem / Brett'), ('hybrid', 'Híbrida / Kveik'), ('other', 'Outra')], default='ale', max_length=20),
        ),
    ]
